news/urls.py
from django.urls import path
from .views import home , articoloDetailView,index3,listaArticoli
app_name = 'news'

urlpatterns = [
    path('', home, name="homepage"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path('index3', index3, name="index3"),
    path('listaArticoli', listaArticoli, name="listaArticoli"),   
]

prima_app/urls.py
from os import path
from django.urls import path
from prima_app.views import homepage
from prima_app.views import welcome
from prima_app.views import lista
from prima_app.views import chi_siamo
from prima_app.views import variabili
from prima_app.views import index
app_name="prima_app"
urlpatterns=[
    path('homepage',homepage,name='homepage'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('index',index,name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from primo_progetto.views import index_root

#app_name = "primo_progetto"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('',index_root,name="index_root"),
    

]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
    

seconda_app/urls.py
from os import path
from django.urls import path
from seconda_app.views import es_if,index2,if_else_elif,es_for

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('es_for',es_for,name='es_for'),
    path('index2',index2,name='index2'),
   
]

news/models.py
from django.db import models

class Giornalista (models.Model):
  """il modello generico di un giornalista"""
  nome = models.CharField(max_length=20)
  cognome = models.CharField(max_length=20)
  anno_di_nascita=models.DateField(blank=True)
  
  def __str__(self):
    return self.nome + " " + self.cognome
  class Meta:
    verbose_name = "Giornalista"
    verbose_name_plural = "Giornalisti"

class Articolo (models.Model):
  """il modello generico di un articolo di news"""
  titolo = models.CharField(max_length=100)
  contenuto = models.TextField()
  giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
  data=models.DateField(auto_now=True, blank=True)
  visualizzazioni=models.IntegerField (default=0, blank=True)
  
  def __str__(self):
    return self.titolo
  class Meta:
    verbose_name = "Articolo"
    verbose_name_plural = "Articoli"

seconda_app/models.py
from django.db import models

# Create your models here.

news/views.py
from django.shortcuts import render ,get_object_or_404 # type: ignore
from django.http import HttpResponse  # type: ignore
from.models import Articolo, Giornalista 

#def home (request):
    #a = ""
   # g = "" 
   # for art in Articolo.objects.all():
   #         a += (art.titolo + "<br>")
   #         
        
   # for gio in Giornalista.objects.all():
   #         g+= (gio.nome + "<br>")
            
   # response = "Articoli:<br>" + a + "<br>Giornalisti: <br>" + g
        
   # return HttpResponse("<h1>" + response + "</h1>")


#def home (request):
 #   a = []
  #  g = []
   # for art in Articolo.objects.all():
    #    a.append(art.titolo)
    #for gio in Giornalista.objects.all():
     #   g.append(gio.nome)
      #  response = str(a) + "<br>" + str(g)
       # print(response)

    #return HttpResponse("<h1>" + response + "</h1>")

def home (request): 
    articoli= Articolo.objects.all() 
    giornalisti =Giornalista.objects.all() 
    context = {"articoli": articoli, "giornalisti": giornalisti} 
    print(context) 
    return render (request, "homepage.html", context)

def articoloDetailView(request, pk): 
    #articolo = Articolo.objects.get(pk=pk) 
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render (request, "articolo_detail.html", context)

def index3(request):
    return render(request,"index3.html")


def listaArticoli (request,pk=None):
    articoli = Articolo.objects.all()
    context = {
        'articoli': articoli,
    }
    return render (request, 'listaArticoli.html', context)

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def welcome(request):
    return render(request,"welcome.html")

def homepage(request):
    return render(request,"homepage.html")

def lista(request):
    return render(request,"lista.html")

def chi_siamo(request):
    return render(request,"chi_siamo.html")

def variabili(request):
    context={
        'var1':'Prima variabile',
        'var2':'Secondo variabile',
        'var3':'Terza variabile',
    }
    return render(request,"variabili.html",context)

def index(request):
    return render(request,"index.html")

primo_progetto/views.py
from django.shortcuts import render

def index_root(request):
    return render(request,"index_root.html")

seconda_app/views.py
from django.shortcuts import render
import datetime
def es_if(request):
     context = { 
          'var1': 200, 
          'var2': 200, 
          'var3': 300 
          } 
     return render(request, "es_if.html", context)

def if_else_elif(request):
     context = { 
          'var1': 100, 
          'var2': 100.0, 
          'var3': 100.50 
          } 
     return render(request, "if_else_elif.html", context)

def es_for(request):
     context = {'list1': [1, datetime.date(2019,7,16), 'Do not give up!'],
                'list2': [1, datetime.date(2019,7,16), 'Do not give up!'] 
     }
     return render(request, "es_for.html", context)

def index2(request):
    return render(request,"index2.html")

news/templates/articolo_detail.html
{% extends 'base.html' %}

{% block title %}
   {{ articolo.titolo }}
{% endblock title %} 

{% block content %} 
    <h1>{{ articolo.titolo }}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{% endblock content %}

news/templates/homepage.html
{% extends 'base.html'%} 
{%block title%} 
Articoli e Giornalisti 
{%endblock title%} 
{%block content%} 
    <h4>Articoli:</h4> 
        {% for articolo in articoli %}
         <p><strong>Titolo: </strong>{{ articolo.titolo }}</p> 
         <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
          <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
           <hr> 
        {% endfor %} 
    <h4>Giornalisti:</h4> 
            {% for giornalista in giornalisti %} 
             <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
             <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
              <hr>
             {% endfor %}
{%endblock content%}

news/templates/index3.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | index3  {%endblock title%}
{%block content%}
    <ol> 
        <li><a href="{% url 'news:homepage'%}">homepage</a></li> 
        <li><a href="{% url 'news:articolo_detail' 1 %}">articolo detail</a></li> 
        <li><a href="{% url 'news:listaArticoli' %}">Lista articoli</a></li> 
        <li><a href="/">Index root</a></li>
    </ol> 
{%endblock content%}

news/templates/listaArticoli.html
{% extends 'base.html' %}

{% block title %}
   {{ articolo.titolo }}
{% endblock title %} 

{% block content %} 
    <ul>
    {%for articolo in articoli %}
        <li>{{articolo}}</li>
    {%endfor%}
    </ul>
{%endblock content%}

prima_app/templates/chi_siamo.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Chi siamo {%endblock title%}
{%block content%}

    <h1>Chi siamoC
    <pr>lorem ipsum</pr>

{%endblock content%}

prima_app/templates/homepage.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Homepage {%endblock title%}
{%block content%}

    <h1>Benvenuto</h1>

{%endblock content%}

prima_app/templates/index.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Index {%endblock title%}
{%block content%}

    <ol> 
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li> 
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li> 
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li> 
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li> 
        <li><a href="/">Index root</a></li>
    </ol> 

{%endblock content%}

prima_app/templates/lista.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Lista {%endblock title%}
{%block content%}

    <ol>Primo</ol> 
    <ol>Secondo</ol> 
    <ol>Terzo</ol> 
    
{%endblock content%}

prima_app/templates/variabili.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Variabili {%endblock title%}
{%block content%}

<ol>
    <li>{{var1}}</li>
    <li>{{var2}}</li>
    <li>{{var3}}</li>
</ol>
    
{%endblock content%}

prima_app/templates/welcome.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Welcome {%endblock title%}
{%block content%}

    <h1>Welcome</h1>
    
{%endblock content%}

seconda_app/templates/es_for.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | es_for {%endblock title%}
{%block content%}
Cicla una sequenza usando <b>forloop.counter</b>
<br/>
{% for x in list2 %}
  <i>{{ forloop.counter }}</i> : {{ x }}<br>
{% endfor %}
<br/>
Cicla una sequenza<b>forloop.counter0</b>
<br/>
{% for x in list2 %}
<i>{{ forloop.counter0 }}</i> : {{ x }}<br>
{% endfor %}
<br/>
Stampa il primo elemento della sequenza usando <b>forloop.first</b>:
<br/>
{% for x in list2 %}
    {% if forloop.first %}
        <i>Il primo elemento</i> - {{x}}
    {% endif%}
{% endfor %}
<br/>
Stampa l'ultimo elemento della lista usando <b>forloop.last</b>: 
<br/>
{% for x in list2 %}
    {% if forloop.last %}
        <i>L'ultimo elemento</i> - {{x}}
    {% endif%}
{% endfor %}
<br/>
Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter</b>: 
<br/>
{% for x in list2 %}
    <i>Numero degli elementi da dover ancora ciclare</i> {{ forloop.revcounter }}<br/>
    <i>Elemento</i> {{x}}<br/>
{% endfor %}
<br/>
Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter</b>:
<br/>
{% for x in list2 %}
    <i>Numero degli elementi da dover ancora ciclare</i> {{forloop.revcounter }}<br/>
    <i>Elemento</i> - {{x}}<br/>
    {% endfor %}
<br/>
Stampa la sequenza al contrario usando <b>reversed</b>, attributo del tag <b>for</b>:
<br/>
{% for x in list2 reversed %} 
    <i>Elemento</i> - {{x}}<br/>
{% endfor %}
{%endblock content%}

seconda_app/templates/es_if.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | es_if {%endblock title%}
{%block content%}
<b>var1 = {{ var1 }}</b> <br/> 
<b>var2 = {{ var2 }}</b> <br/> 
<b>var3 = {{ var3 }}</b> <br/> 
{% if var1 < var2 %} 
 <p><i>var1 è minore di var2 </i></p> 
{% endif %} 
{% if var1 > var2 %} 
 <p><i>var1 è maggiore di var2 </i></p> 
{% endif %} {% if var1 <= var2 %} 
<p><i>var1 è minore o ugua1e di var2 </i></p> 
{% endif %} 
{% if var1 >= var2 %} 
 <p><i>var1 è maggiore o ugua1e di var2 </i></p> 
{% endif %} 
{% if var1 == var2 %} 
 <p><i>var1 è ugua1e a var2 </i></p> 
{% endif %} {% if var1 != var2 %} 
 <p><i>var1 non è ugua1e a var2 </i></p> 
{% endif %} 
{% if var1 < var2 and var1 < var3 %} 
 <p><i>var1 è minore di var2 e var1 è minore di var3 </i></p> 
{% endif %} {% if var1 < var2 or var3 < var2 %} 
 <p><i>var1 è minore di var2 o var3 è minore di var2 </i></p> 
{% endif %} 
{% if not var1 > var2 %} 
 <p><i>var1 non è maggiore di var2 </i></p> 
{% endif %}
{%endblock content%}

seconda_app/templates/if_else_elif.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | if_else_elif {%endblock title%}
{%block content%}
    <b>var1 = {{ var1 }}</b> <br />
    <b>var2 = {{ var2 }}</b> <br />
    <b>var3 = {{ var3 }}</b> <br />
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2 </i></p>
    {% elif var1 > var2%}
        <p><i>var1 è maggiore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale di var2</i></p>
    {% endif %}
    {% if var1 > var2%}
        <p><i>var1 è maggiore di var2</i></p>
    {% elif var1 < var2%}
        <p><i>var1 è minore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale di var2</i></p>
    {% endif %}
    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale a var2 </i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% endif %}
    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale a var2</i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% endif %}
    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2 </i></p>
    {% elif var1 != var2 %}
        <p><i>var1 non è uguale a var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 e di var3 </i></p>
    {% elif var1 > var2 and var1 > var3 %}
        <p><i>var1 è maggiore di var2 e di var3 </i></p>
    {% endif %}
    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore di var2 </i></p>
    {% elif not var1 < var2 %}
        <p><i>var1 non è minore di var2 </i></p>
    {% else %}
        <p><i>var1 è uguale a var2 </i></p>
    {% endif %}
    

{%endblock content%}

seconda_app/templates/index2.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | Index2  {%endblock title%}
{%block content%}
    <ol> 
        <li><a href="{% url 'seconda_app:es_if'%}">es_if</a></li> 
        <li><a href="{% url 'seconda_app:if_else_elif'%}">if_else_elif</a></li>
        <li><a href="{% url 'seconda_app:es_for'%}">es_for</a></li>
        <li><a href="/">Index root</a></li>
    </ol> 
{%endblock content%}

templates/base.html
{% load static %}
<!doctype html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">primo progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              prima app
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'prima_app:welcome' %}">welcome</a>
              <a class="dropdown-item" href="{% url 'prima_app:lista' %}">lista</a>
              <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">homepage</a>
              <a class="dropdown-item" href="{% url 'prima_app:chi_siamo' %}">chi siamo</a>
              <a class="dropdown-item" href="{% url 'prima_app:index' %}">index</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              seconda app
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'seconda_app:es_for' %}">es_for</a>
              <a class="dropdown-item" href="{% url 'seconda_app:es_if' %}">es_if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif' %}">if_else_elif</a>
              <a class="dropdown-item" href="{% url 'seconda_app:index2' %}">index</a>
              
              
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              news
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'news:articolo_detail' 1%}">articolo_detail</a>
              <a class="dropdown-item" href="{% url 'news:homepage' %}">homepage</a>
              <a class="dropdown-item" href="{% url 'news:index3' %}">index3</a>
              
              
            </div>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="dropdown-divider"></div>
            <form id="logout-form" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="btn ft-power" type="submit">Logout</button>
            </form>
            </div>
            </li>
        {% else %}
            
            <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}
         
        </ul>
       
      </div>
    </nav>
    <div class="container my-4">
      <!--servirà per inserire i contenuti della pagina-->
      {%block content%}
      {%endblock%}
      <!--serrvirà per inserire il codice javascript-->
      {%block script%}
      {%endblock script%}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index_root.html
{% extends "base.html"%}

{%block title%} {{block.super}} primo_progetto | IndexRoot {%endblock title%}
{%block content%}

    <h1></h1>
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href=" {% url 'prima_app:index'%}">Prima app</a></li>
        <li><a href=" {% url 'seconda_app:index2'%}">Seconda app</a></li>
        <li><a href=" {% url 'news:index3'%}">news</a></li>
    </ol>

{%endblock content%}